ImportCrossReferences:
    information:
        text:    Imports cross-references to the active model
        tooltip: This tool allows you to import a tab seperated value (TSV) table of
                 identifiers and their cross-references into Metingear.
        active:  true
    okay:
        text:    Import
    browse:
        text:    Browse
        tooltip: Load a file from the file system
        icon:    /uk/ac/ebi/chemet/render/images/cutout/browse_16x16.png
    selected:
        text:    "Selected:"
    header:
        text:    "Header:"
        tooltip: Is the header the first row?
    separator:
        text:    "Separator:"
        tooltip: How are your columns separated?
    mapTo:
        text:    "Map With:"
        tooltip: How to pair the cross-references with the model
    mode:
        text:    "Mode:"
        tooltip: How should the cross-references be imported?
    infer:
        text:    Resource Inference
        tooltip: Infer what a resource is by what the idenfier looks like, ambiguous identifiers will be skipped
    single:
        text:    Single Resource
    mapped:
        text:    Column Mapping
    inferArea:
        text:    Load data from two columns, the first column is the identifier/abreviation in the model and
                 the second is the cross-reference. The resource of the cross-reference is automatically infered
                 from pattern matching. If the resource can not be matched the cross-reference is not imported.
    singleArea:
        text:    Load data from two columns, the first column is the identifier/abreviation in the model and
                 the second is the cross-reference. The identifiers are loaded as the selected resources
                 resource below. Only identifiers which match the internal pattern are loaded.
    mappedArea:
        text:    Load data from three columns, the first column is the identifier/abreviation in the model and
                 the second is the cross-reference. The third column specifies the identifier type as it appears
                 in the MIRIAM registry, for example, you must specify 'KEGG Compound' instead of 'KEGG'. For a
                 full list of valid identifiers please refer to http://www.ebi.ac.uk/miriam/main/.
    dest:
        text:    "Destination:"
        tooltip: Select one or more entities to which you which to map the loaded identifiers
